version: '3.8'

services:
  db:
    image: cassandra:5.0
    container_name: cassandra_db
    environment:
      CASSANDRA_CLUSTER_NAME: "news_db"
      CASSANDRA_DC: "My_DC1"
      CASSANDRA_RACK: "My_Rack1"
      CASSANDRA_SEEDS: "cassandra_db"
      CASSANDRA_USERNAME: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  app:
    build:
      context: .
    container_name: news_app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  cassandra_data: